# Site settings
title: Adithya Selvaprithiviraj
tagline: (Philomath)
email: adithyaselv@gmail.com
description: > # 
  My personal website and blog.
  
url: "http://adithyaselv.com/" # the base hostname & protocol for your site   adithyaselv.com/    127.0.0.1:4000/
logourl: /assets/images/logo1.png # Site logo
author: "Adithya Selvaprithiviraj"
author_thumbnail: "/assets/images/profile.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme2:
  # Color for sidebar bar, links, etc
  highlight_color: "#272935" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: adithyaselv
    twitter: adiselv
    facebook: adithya.selv
    gplus: 108226416859048858371 


  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true


  # Disqus comments manager - shortname
  disqus_shortname: adithyaselv

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-64328759-1 
  google_webmaster_key: 

# Build settings
markdown: kramdown

#gems
gems: [jekyll-paginate] 

# Permalinks
permalink: pretty

# Pagination config
paginate: 3
paginate_path: "/blog/page:num/"

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
